In [1]:
from PIL import Image
import pandas as pd
from multiprocessing import  Pool
import numpy as np

In [2]:
#change to reflect your image directory and annotations file
img_dir = '/domino/datasets/local/snapshot-serengeti-images/snapshotserengeti-unzipped'
annotations_file = '/mnt/dataset_labels.csv'

labels = pd.read_csv(annotations_file, low_memory=False)
labels.head()

,capture_id,image_name,season,site,roll,capture,capture_date_local,capture_time_local,subject_id,question__species,...,question__count_min,question__standing,question__resting,question__moving,question__eating,question__interacting,question__young_present,p_users_identified_this_species,pielous_evenness_index,question__horns_visible
0,SER_S1#B04#1#6,S1_B04_R1_PICT0006.JPG,S1,B04,1,6,2010-07-24,08:20:10,ASG0002kjm,gazelleGrants,...,1,0.00,0.0,1.00,0.0,0.0,0.00,0.52,0.70,NaN
1,SER_S1#B04#1#8,S1_B04_R1_PICT0008.JPG,S1,B04,1,8,2010-07-30,03:59:42,ASG0002kjo,dikDik,...,1,0.81,0.0,0.19,0.0,0.0,0.00,0.84,0.48,NaN
2,SER_S1#B05#1#3,S1_B05_R1_PICT0004.JPG,S1,B05,1,3,2010-07-20,15:23:10,ASG0000003,blank,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,0.00,NaN
3,SER_S1#B05#1#9,S1_B05_R1_PICT0017.JPG,S1,B05,1,9,2010-07-27,00:54:32,ASG0000009,hyenaSpotted,...,1,0.07,0.0,0.93,0.0,0.0,0.00,0.74,0.58,NaN
4,SER_S1#B05#1#14,S1_B05_R1_PICT0027.JPG,S1,B05,1,14,2010-07-28,18:04:14,ASG000000e,impala,...,1,1.00,0.0,0.00,0.0,0.0,0.08,0.52,0.75,NaN

In [ ]:
#check if image loads
def check_image(img):
    try:
        with Image.open(img) as im:
            im.load()
        return False
    except:
        return True

In [ ]:
#add labels for corrupted images
def check_image_df(df):
    df['corrupt'] = df['image_name'].apply(lambda img: check_image(img_dir+'/'+img))
    return df

In [ ]:
def parallelize_dataframe(df, func, n_cores=4):
    df_split = np.array_split(df, n_cores)
    pool = Pool(n_cores)
    df = pd.concat(pool.map(func, df_split))
    pool.close()
    pool.join()
    return df

In [ ]:
#save
labels = parallelize_dataframe(labels, check_image_df, n_cores=12)
labels.to_csv('/mnt/dataset_labels_w_corrupt.csv', index=False)
labels.loc[labels['corrupt'] == True].head()

In [3]:
labels = pd.read_csv('/mnt/dataset_labels_w_corrupt.csv', low_memory=False)
labels.loc[labels['corrupt'] == True]

,capture_id,image_name,season,site,roll,capture,capture_date_local,capture_time_local,subject_id,question__species,...,question__standing,question__resting,question__moving,question__eating,question__interacting,question__young_present,p_users_identified_this_species,pielous_evenness_index,question__horns_visible,corrupt
16328,SER_S1#I03#1#1208,S1_I03_R1_PICT3739.JPG,S1,I03,1,1208,2010-09-26,12:44:26,ASG00018jx,blank,...,NaN,NaN,NaN,NaN,NaN,NaN,1.00,0.00,NaN,True
27564,SER_S1#O05#1#1155,S1_O05_R1_PICT3588.JPG,S1,O05,1,1155,2010-09-17,13:32:54,ASG000208d,blank,...,NaN,NaN,NaN,NaN,NaN,NaN,1.00,0.00,NaN,True
27573,SER_S1#O05#1#1195,S1_O05_R1_PICT3840.JPG,S1,O05,1,1195,2010-09-18,10:45:18,ASG00020aq,blank,...,NaN,NaN,NaN,NaN,NaN,NaN,1.00,0.00,NaN,True
27574,SER_S1#O05#1#1197,S1_O05_R1_PICT3845.JPG,S1,O05,1,1197,2010-09-18,10:49:22,ASG00020as,blank,...,NaN,NaN,NaN,NaN,NaN,NaN,1.00,0.00,NaN,True
27599,SER_S1#O05#1#1304,S1_O05_R1_PICT4351.JPG,S1,O05,1,1304,2010-09-20,10:11:38,ASG00020fh,blank,...,NaN,NaN,NaN,NaN,NaN,NaN,1.00,0.00,NaN,True
27604,SER_S1#O05#1#1352,S1_O05_R1_PICT4607.JPG,S1,O05,1,1352,2010-09-21,09:15:10,ASG00020hv,blank,...,NaN,NaN,NaN,NaN,NaN,NaN,1.00,0.00,NaN,True
241512,SER_S5#D11#2#16,S5_D11_R2_IMAG0044.JPG,S5,D11,2,16,2012-08-11,14:42:20,ASG000ob1u,gazelleThomsons,...,1.0,0.0,0.0,0.0,0.0,0.0,0.91,0.44,NaN,True
353612,SER_S7#B05#1#1,S7_B05_R1_IMAG0001.JPG,S7,B05,1,1,2013-04-08,11:25:16,ASG0018eus,blank,...,NaN,NaN,NaN,NaN,NaN,NaN,0.83,0.00,NaN,True
427817,SER_S7#T12#1#67,S7_T12_R1_IMAG0179.JPG,S7,T12,1,67,2013-02-11,23:55:49,ASG0012iq9,lionFemale,...,0.0,0.0,1.0,0.0,0.0,0.0,1.00,0.00,NaN,True
427822,SER_S7#T12#1#71,S7_T12_R1_IMAG0203.JPG,S7,T12,1,71,2013-02-17,11:04:59,ASG0012irh,baboon,...,0.3,0.0,0.7,0.0,0.0,0.0,0.91,0.44,NaN,True
497214,SER_S8#N04#2#165,S8_N04_R2_IMAG0458.JPG,S8,N04,2,165,2014-04-07,15:11:51,ASG001dewd,wildebeest,...,1.0,0.0,0.0,0.0,0.0,0.0,0.67,0.73,NaN,True
510633,SER_S8#P08#2#270,S8_P08_R2_IMAG0796.JPG,S8,P08,2,270,2014-03-11,12:33:36,ASG0018x9q,blank,...,NaN,NaN,NaN,NaN,NaN,NaN,1.00,0.00,NaN,True
557010,SER_S9#F04#2#1039,S9_F04_R2_IMAG2759.JPG,S9,F04,2,1039,2014-10-29,12:45:31,ASG001jegw,topi,...,0.0,0.0,1.0,0.0,0.0,0.0,0.59,0.73,NaN,True
610446,SER_S9#Q10#3#2408,S9_Q10_R3_IMAG7046.JPG,S9,Q10,3,2408,2014-12-02,23:00:10,ASG001njlg,zebra,...,0.9,0.0,0.1,0.1,0.0,0.1,1.00,0.00,NaN,True
667453,SER_S10#N05#1#180,S10_N05_R1_IMAG0482.JPG,S10,N05,1,180,2015-01-11,11:13:57,ASG001z416,blank,...,NaN,NaN,NaN,NaN,NaN,NaN,0.59,0.00,NaN,True
667455,SER_S10#N05#1#181,S10_N05_R1_IMAG0486.JPG,S10,N05,1,181,2015-01-11,11:19:23,ASG001z2no,wildebeest,...,0.6,0.6,0.8,0.7,0.1,0.1,1.00,0.00,NaN,True
684105,SER_S10#R08#1#668,S10_R08_R1_IMAG1689.JPG,S10,R08,1,668,2015-02-07,16:43:58,ASG001u1v0,blank,...,NaN,NaN,NaN,NaN,NaN,NaN,1.00,0.00,NaN,True